---
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/potato-face?
  value:
    access-token-validity: 120
    authorized-grant-types: client_credentials
    override: true
    secret: ((client-secret))
    scope: openid,routing.router_groups.write,scim.read,cloud_controller.admin,uaa.user,routing.router_groups.read,cloud_controller.read,password.write,cloud_controller.write,network.admin,doppler.firehose,scim.write
    authorities: openid,routing.router_groups.write,scim.read,cloud_controller.admin,uaa.user,routing.router_groups.read,cloud_controller.read,password.write,cloud_controller.write,network.admin,doppler.firehose,scim.write

