#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() { 
  setup_bosh_env_vars
  run_smoke_tests
  close_bbl_ssh_connection
}

function run_smoke_tests() {
  bosh -d cf run-errand smoke-tests
}

main
