---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: phusion/baseimage

inputs:
  - name: bbl-state
  - name: cli-ci
  - name: vars-store

outputs:
  - name: updated-vars-store

params:
  BBL_STATE_DIR:
  CLIENT_SECRET:
  SYSTEM_DOMAIN:
  VARS_FILE:
  VARS_STORE_FILE:

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    curl https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-3.0.1-linux-amd64 -o /usr/bin/bosh
    chmod +x /usr/bin/bosh

    curl -L https://github.com/cloudfoundry/bosh-bootloader/releases/download/v6.7.0/bbl-v6.7.0_linux_x86-64 -o /usr/bin/bbl
    chmod +x /usr/bin/bbl

    bbl_state_path="bbl-state/${BBL_STATE_DIR}"
    cli_operations_dir="cli-ci/ci/infrastructure/operations"

    pushd $bbl_state_path
      eval "$(bbl print-env)"
    popd

    bosh upload-stemcell -n "https://s3.amazonaws.com/bosh-gce-light-stemcells/light-bosh-stemcell-3312.51-google-kvm-ubuntu-trusty-go_agent.tgz"

    cat << EOF > vars.yml
    client-secret: ${CLIENT_SECRET}
    EOF

    bosh -d cf deploy cli-ci/ci/infrastructure/assets/legacy-cf-deployment.yml -n \
      -o $cli_operations_dir/legacy/gcp.yml \
      -o $cli_operations_dir/legacy/scale-to-one-az.yml \
      -o $cli_operations_dir/legacy/add-reserved-routes.yml \
      -o $cli_operations_dir/uaa-vm_type-override.yml \
      -o $cli_operations_dir/default-app-memory.yml \
      -o $cli_operations_dir/diego-cell-instances.yml \
      -o $cli_operations_dir/add-uaa-client-credentials.yml \
      -v system_domain=$SYSTEM_DOMAIN \
      --vars-store="vars-store/${VARS_STORE_FILE}" \
      --vars-file=./vars.yml

    pushd vars-store
      if [[ -n $(git status --porcelain) ]]; then
        git config user.name "Concourse CI"
        git config user.email "cf-cli-eng@pivotal.io"

        git add "${VARS_STORE_FILE}"
        git commit -m "Update vars-store after legacy deploy"
      fi
    popd

    shopt -s dotglob
    cp -R vars-store/* updated-vars-store/

