
additionalRepositories:
  - url: https://github.com/cloudfoundry/cli-ci    
    checkoutLocation: cli-ci
  - url: https://github.com/cloudfoundry/cli-private    
    checkoutLocation: cli-private

tasks:
  - name: Setup Workspace
    before: >
      sudo apt install --yes 
      icdiff
      tldr
      fzf

      brew install
      asdf
    init: >
      tldr --update 
      
      make clean build
    command: out/cf version

vscode:
  extensions:
    - vscodevim.vim
    - eamodio.gitlens
