---
resources:
- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    submodules: true
    tag_filter: "v6*"
    ignore_paths:
    - ci

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths:
    - ci

- name: homebrew-tap
  type: git
  source:
    uri: git@github.com:cloudfoundry/homebrew-tap
    private_key: {{homebrew-tap-github-private-key}}
    branch: master

- name: edge-linux-binary-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli_edge_linux_i686.tgz
    region_name: us-west-1

- name: edge-linux-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli_edge_linux_x86-64.tgz
    region_name: us-west-1

- name: edge-osx-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli_edge_osx.tgz
    region_name: us-west-1

- name: edge-windows-binary-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli_edge_winx64.zip
    region_name: us-west-1

- name: edge-deb-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_i686.deb
    region_name: us-west-1

- name: edge-deb-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_x86-64.deb
    region_name: us-west-1

- name: edge-redhat-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_i686.rpm
    region_name: us-west-1

- name: edge-redhat-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_x86-64.rpm
    region_name: us-west-1

- name: edge-osx-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-release-access-key-id}}
    secret_access_key: {{cli-production-release-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_osx.pkg
    region_name: us-west-1

jobs:
- name: create-and-sign-installers
  serial: true
  plan:
  - aggregate:
    - get: cli
    - get: cli-ci
    - get: edge-linux-binary-32
    - get: edge-linux-binary-64
    - get: edge-osx-binary-64
    - get: edge-windows-binary-32
    - get: edge-windows-binary-64
    - get: edge-deb-installer-32
    - get: edge-deb-installer-64
    - get: edge-redhat-installer-32
    - get: edge-redhat-installer-64
    - get: edge-osx-installer-64

  - task: obtain-certificates
    file: cli-ci/ci/cli-release/tasks/obtain-certificates.yml
    params:
      CERT_PATH: {{osx-certificate-store}}
  - task: copy-certificates
    file: cli-ci/ci/cli-release/tasks/copy-certificates.yml

  - aggregate:
    - task: repackage-binaries-and-installers
      file: cli-ci/ci/cli-release/tasks/repackage-binaries-and-installers.yml

    - task: sign-osx-installer
      file: cli-ci/ci/cli-release/tasks/sign-osx-installer.yml
      params:
        CERT_COMMON_NAME: {{osx-certificate-common-name}}
        CERT_LOCATION: {{osx-certificate-location}}
        CERT_PASSWORD_LOCATION: {{osx-certificate-password-location}}

    - task: sign-redhat-installers
      file: cli-ci/ci/cli-release/tasks/sign-redhat-installers.yml
      params:
        GPG_KEY_LOCATION: {{gpg-key-location}}

    - do:
      - task: sign-windows-binaries
        file: cli-ci/ci/cli-release/tasks/sign-windows-binaries.yml
        params:
          CERT_LOCATION: {{windows-certificate-location}}
          CERT_PASSWORD_LOCATION: {{windows-certificate-password-location}}
      - task: create-windows-installers
        file: cli-ci/ci/cli/tasks/create-installers-windows.yml
      - task: sign-and-repackage-installers-and-binaries
        file: cli-ci/ci/cli-release/tasks/sign-and-repackage-installers-and-binaries.yml
        params:
          CERT_LOCATION: {{windows-certificate-location}}
          CERT_PASSWORD_LOCATION: {{windows-certificate-password-location}}

  - task: upload-releases
    file: cli-ci/ci/cli-release/tasks/upload-releases.yml
    params:
      AWS_ACCESS_KEY_ID: {{cli-production-release-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{cli-production-release-secret-access-key}}

- name: update-claw
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [create-and-sign-installers]
    - get: cli-ci
    - get: edge-linux-binary-64
      passed: [create-and-sign-installers]
  - aggregate:
    - task: claw.run.pivotal.io
      file: cli-ci/ci/cli-release/tasks/update-claw.yml
      params:
        CF_API: {{cf-api}}
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        CF_ORGANIZATION: {{pivotal-organization}}
        CF_SPACE: {{pivotal-space}}
    - task: packages.cloudfoundry.org
      file: cli-ci/ci/cli-release/tasks/update-claw.yml
      params:
        CF_API: {{cf-api}}
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        CF_ORGANIZATION: {{oss-organization}}
        CF_SPACE: {{oss-space}}

- name: update-debian-repo
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [update-claw]
    - get: cli-ci
  - task: obtain-certificates
    file: cli-ci/ci/cli-release/tasks/obtain-certificates.yml
    params:
      CERT_PATH: {{osx-certificate-store}}
  - task: copy-certificates
    file: cli-ci/ci/cli-release/tasks/copy-certificates.yml
  - task: publish-debian
    file: cli-ci/ci/cli-release/tasks/publish-debian.yml
    params:
      AWS_ACCESS_KEY_ID: {{cli-production-release-access-key-id}}
      AWS_BUCKET_NAME: cf-cli-debian-repo
      AWS_SECRET_ACCESS_KEY: {{cli-production-release-secret-access-key}}
      GPG_KEY_LOCATION: {{gpg-key-location}}
      KEY_ID_LOCATION: {{gpg-key-id-location}}

- name: update-homebrew
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [update-claw]
    - get: cli-ci
    - get: homebrew-tap
  - task: update-brew-formula
    file: cli-ci/ci/cli-release/tasks/update-brew-formula.yml
  - put: homebrew-tap
    params:
      repository: update-brew-formula-output/homebrew-tap

- name: update-rpm-repo
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [update-claw]
    - get: cli-ci
  - task: obtain-certificates
    file: cli-ci/ci/cli-release/tasks/obtain-certificates.yml
    params:
      CERT_PATH: {{osx-certificate-store}}
  - task: copy-certificates
    file: cli-ci/ci/cli-release/tasks/copy-certificates.yml
  - task: publish-rpm
    file: cli-ci/ci/cli-release/tasks/publish-rpm.yml
    params:
      AWS_ACCESS_KEY_ID: {{cli-production-release-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{cli-production-release-secret-access-key}}
      GPG_KEY_LOCATION: {{gpg-key-location}}
