#!/bin/sh

while read LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA
do
  if git show $LOCAL_SHA --format=fuller | grep -i -q 'Commit: \+pivotal '; then
    echo "Committer on $LOCAL_SHA is Pivotal."
    echo 'Please run "git fr".'
    exit 1
  fi
done
