#!/bin/bash

set -e -x

mkdir cf-cli/out
mv darwin64-binary/cf-* cf-cli/out/cf-darwin-amd64
mv linux64-binary/cf-* cf-cli/out/cf-linux-amd64
mv linux32-binary/cf-* cf-cli/out/cf-linux-386
mv windows64-binary/cf-* cf-cli/out/cf-windows-amd64.exe
mv windows32-binary/cf-* cf-cli/out/cf-windows-386.exe

export S3_CONFIG_FILE=${PWD}/cli-ci/ci/s3cfg

cd cf-cli

chmod +x out/cf-darwin-amd64
chmod +x out/cf-linux-386
chmod +x out/cf-linux-amd64
chmod +x out/cf-windows-amd64.exe
chmod +x out/cf-windows-386.exe

ci/scripts/build-installers-concourse
ci/scripts/tar-executables
ci/scripts/upload-binaries-concourse
