#!/bin/bash

git fetch --tags
git checkout $GIT_COMMIT

ci/scripts/retrieve-binaries
ci/scripts/build-installers
ci/scripts/upload-binaries
( /bin/bash --login -c "rvm use 1.9 && bin/pivotal-tracker-deliver"; exit 0 )
