#!/usr/bin/env bash

set -e -x

export CF_RAISE_ERROR_ON_WARNINGS=true

export CONFIG_DIR=${PWD}

export CLI_DIR=$(cd $(dirname $0)/../.. && pwd)

export GOPATH=${PWD}/gopath
export PATH=${GOPATH}/bin:${PATH}
export CF_RELEASE_DIR=${PWD}/cf-release

export API_ENDPOINT="https://api.${BOSH_LITE_IP}.xip.io"
export API="https://api.${BOSH_LITE_IP}.xip.io"
export APPS_DOMAIN="${BOSH_LITE_IP}.xip.io"
export CC_HOSTNAME="api.${BOSH_LITE_IP}.xip.io"
export BOSH_LITE_HOSTNAME="ubuntu@${BOSH_LITE_IP}"

ADMIN_USER="admin" ADMIN_PASSWORD="admin" \
  CF_USER="user" CF_PASSWORD="userpassword" \
  CF_ORG="cli-cats-org" CF_SPACE="cli-cats-space" \
  ${CLI_DIR}/ci/scripts/create-cats-config

export CATSPATH=${GOPATH}/src/github.com/cloudfoundry/cf-acceptance-tests
export RELEASEPATH=${GOPATH}/src/github.com/cloudfoundry/cf-release
export CATS_GOPATH=${CATSPATH}/Godeps/_workspace

# move cats into gopath
mkdir -p ${CATSPATH}
#cp -r ${CF_RELEASE_DIR}/src/acceptance-tests/* ${CATSPATH}

git clone https://github.com/cloudfoundry/cf-release ${RELEASEPATH}
pushd $RELEASEPATH
  export CATS_SHA=$(git submodule | grep acceptance-tests | awk '{print $1;}' | cut -d "-" -f 2)
popd  
rm -rf $RELEASEPATH

git clone https://github.com/cloudfoundry/cf-acceptance-tests ${CATSPATH}
export GOPATH=${CATS_GOPATH}:${GOPATH}
export PATH=${CATS_GOPATH}/bin:${PATH}

# add prebuilt cf cli to the $PATH
mkdir ${CATS_GOPATH}/bin
install linux64-binary/cf-* ${CATS_GOPATH}/bin/cf

set +x
echo "************ DEBUG"
echo "ENV:"
echo
env
set -x

# run cats
pushd ${CATSPATH}
  git checkout $CATS_SHA
  echo CATs is now at $CATS_SHA
  go install github.com/onsi/ginkgo/ginkgo

  CONFIG=${CONFIG_DIR}/config.json \
    ginkgo \
    -r \
    -slowSpecThreshold=120 \
    -skipPackage='logging,services,v3,routing_api' \
    -skip="go makes the app reachable via its bound route|SSO|takes effect after a restart, not requiring a push|doesn't die when printing 32MB"
popd
