#!/usr/bin/env bash

set -ex

mkdir -p out release
(
  cd out

  ls cf-cli*

  for BIN in cf-cli_[lo]*; do # linux, osx
    cp ${BIN} cf
    tar cvzf ../release/${BIN}.tgz cf
    rm cf
  done

  for BIN in cf-cli_win*; do
    cp ${BIN} cf.exe
    zip ../release/${BIN%exe}zip cf.exe
    rm cf.exe
  done
)
