#!/usr/bin/env bash

function printStatus {
  if [ $? -eq 0 ]; then
      echo -e "\nPOP POP POP POP POP POP POP"
  else
      echo -e "\nMAN DOWN"
  fi
}

trap printStatus EXIT

set -e -x

export CLI_DIR=$(cd $(dirname $0)/../.. && pwd)

export CF_RAISE_ERROR_ON_WARNINGS=true

export CONFIG_DIR=${PWD}
export GOPATH=${PWD}/gopath
export PATH=${GOPATH}/bin:${PATH}
export CF_RELEASE_DIR=${PWD}/cf-release

export API_ENDPOINT="https://api.${BOSH_LITE_IP}.xip.io"
export API="https://api.${BOSH_LITE_IP}.xip.io"
export APPS_DOMAIN="${BOSH_LITE_IP}.xip.io"
export CC_HOSTNAME="api.${BOSH_LITE_IP}.xip.io"
export BOSH_LITE_HOSTNAME="ubuntu@${BOSH_LITE_IP}"

ADMIN_USER="admin" ADMIN_PASSWORD="admin" \
  CF_USER="user" CF_PASSWORD="userpassword" \
  CF_ORG="cli-cats-org" CF_SPACE="cli-cats-space" \
  ${CLI_DIR}/ci/scripts/create-cats-config

GATSPATH=$PWD/gopath/src/github.com/cloudfoundry/GATS
GATS_GOPATH=${GATSPATH}/Godeps/_workspace

export GOPATH=${GATS_GOPATH}:$GOPATH
export PATH=${GATS_GOPATH}/bin:$PATH

# add prebuilt cf cli to the $PATH
mkdir ${GATS_GOPATH}/bin
install linux64-binary/cf-* ${GATS_GOPATH}/bin/cf

cd $GATSPATH

go install github.com/onsi/ginkgo/ginkgo

cp $CONFIG_DIR/config.json unix-gats.json
export CONFIG=`pwd`/unix-gats.json

ginkgo -r -slowSpecThreshold=120 ./gats
