---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cli-ci

params:
  CERT_PATH:

inputs:
  - name: certificates-osx

outputs:
  - name: certificates

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cp -a certificates-osx/* certificates
