---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    ignore_paths:
    - ci
    - integration

- name: cli-i18n
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-i18n
    branch: master

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths:
    - bin
    - ci

- name: cli-integration
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths:
    - integration

- name: cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/vitreuz/cf-acceptance-tests # Temporary fix until PR is merged
    branch: master

- name: cf-cli-binaries
  type: s3
  source:
    bucket: {{staging-bucket-name}}
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: cf-cli-binaries.tgz

- name: edge-linux-binary-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_linux_i686.tgz
    region_name: us-west-1

- name: edge-linux-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_linux_x86-64.tgz
    region_name: us-west-1

- name: edge-osx-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_osx.tgz
    region_name: us-west-1

- name: edge-windows-binary-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-binary-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli_edge_winx64.zip
    region_name: us-west-1

- name: edge-deb-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_i686.deb
    region_name: us-west-1

- name: edge-deb-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_x86-64.deb
    region_name: us-west-1

- name: edge-redhat-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_i686.rpm
    region_name: us-west-1

- name: edge-redhat-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_x86-64.rpm
    region_name: us-west-1

- name: edge-osx-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_osx.pkg
    region_name: us-west-1

- name: edge-windows-installer-32
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-installer-64
  type: s3
  source:
    bucket: cf-cli-releases
    access_key_id: {{cli-production-access-key-id}}
    secret_access_key: {{cli-production-secret-access-key}}
    versioned_file: master/cf-cli-installer_edge_winx64.zip
    region_name: us-west-1

- name: gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: {{cli-pools-github-private-key}}
    branch: master
    pool: bosh-lites-diego

- name: cf-cli-tracker
  type: tracker
  source:
    token: {{cf-cli-public-tracker-token}}
    project_id: {{cf-cli-public-tracker-project-id}}
    tracker_url: https://www.pivotaltracker.com

- name: golang
  type: docker-image
  source:
    repository: golang
    tag: latest

- name: baseimage
  type: docker-image
  source:
    repository: phusion/baseimage
    tag: latest

- name: cli-ci-base-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: [ci/cli-base/Dockerfile]

- name: cli-ci-package-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: [ci/cli-package/Dockerfile]

- name: cf-cli-base-image
  type: docker-image
  source:
    repository: cfcli/cli-base
    username: {{dockerhub-username}}
    email: {{dockerhub-email}}
    password: {{dockerhub-password}}

- name: cf-cli-package-image
  type: docker-image
  source:
    repository: cfcli/cli-package
    username: {{dockerhub-username}}
    email: {{dockerhub-email}}
    password: {{dockerhub-password}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

- name: vars-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: {{cli-private-github-private-key-write}}
    branch: master

groups:
- name: cli
  jobs:
  - units
  - build-binaries
  - integration-linux
  - integration-windows
  - cats
  - integration-experimental
  - create-installers
- name: images
  jobs:
  - create-cli-base-image
  - create-cli-package-image

jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
    - get: cli-ci
  - aggregate:
    - task: units-linux
      file: cli-ci/ci/cli/tasks/units-linux.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             Linux unit tests failed :(
             https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    - task: units-osx
      file: cli-ci/ci/cli/tasks/units-osx.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             OS X unit tests failed :(
             https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    - task: units-windows
      file: cli-ci/ci/cli/tasks/units-windows.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             Windows unit tests failed :(
             https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: build-binaries
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [units]
    - get: cli-ci
    - get: cli-i18n
  - task: build-i18n
    file: cli-ci/ci/cli/tasks/generate-i18n-resources.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-eng'
         text: |
           i18n generation failed :(
           https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - aggregate:
    - task: build
      file: cli-ci/ci/cli/tasks/build-binaries.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             build binaries failed :(
             https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    - task: build-osx
      file: cli-ci/ci/cli/tasks/build-osx-binary.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             build OS X binaries failed :(
             https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - task: combine-binaries
    file: cli-ci/ci/cli/tasks/combine-binaries.yml
  - put: cf-cli-binaries
    params:
      file: compiled/cf-cli-binaries.tgz

- name: integration-linux
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [build-binaries]
    - get: cf-cli-binaries
      passed: [build-binaries]
      trigger: true
    - get: cli-ci
    - get: cli-integration
    - get: vars-store
    - put: bosh-lite-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      file: cli-ci/ci/cli/tasks/cleanup-integration.yml
    - task: integration
      file: cli-ci/ci/cli/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-eng'
          text: |
            Linux integration failed :(
            https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli/tasks/cleanup-integration.yml
      params:
        CF_INT_DOCKER_IMAGE: {{dockerhub-private-image}}
        CF_INT_DOCKER_USERNAME: {{dockerhub-username}}
        CF_INT_DOCKER_PASSWORD: {{dockerhub-password}}
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lite-lock

- name: integration-windows
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [build-binaries]
    - get: cf-cli-binaries
      passed: [build-binaries]
      trigger: true
    - get: cli-ci
    - get: cli-integration
    - get: vars-store
    - put: bosh-lite-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      file: cli-ci/ci/cli/tasks/cleanup-integration.yml
    - task: integration
      file: cli-ci/ci/cli/tasks/integration-windows.yml
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-eng'
          text: |
            Windows integration failed :(
            https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli/tasks/cleanup-integration.yml
      params:
        CF_INT_DOCKER_IMAGE: {{dockerhub-private-image}}
        CF_INT_DOCKER_USERNAME: {{dockerhub-username}}
        CF_INT_DOCKER_PASSWORD: {{dockerhub-password}}
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lite-lock

- name: integration-experimental
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [build-binaries]
    - get: cf-cli-binaries
      passed: [build-binaries]
      trigger: true
    - get: cli-ci
    - get: cli-integration
    - get: vars-store
    - put: bosh-lite-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      file: cli-ci/ci/cli/tasks/cleanup-integration.yml
    - task: integration-windows
      file: cli-ci/ci/cli/tasks/integration-experimental-windows.yml
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-eng'
          text: |
            Windows integration-experimental failed :(
            https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli/tasks/cleanup-integration.yml
      params:
        CF_INT_DOCKER_IMAGE: {{dockerhub-private-image}}
        CF_INT_DOCKER_USERNAME: {{dockerhub-username}}
        CF_INT_DOCKER_PASSWORD: {{dockerhub-password}}
    - task: integration-linux
      file: cli-ci/ci/cli/tasks/integration-experimental-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-eng'
          text: |
            Linux integration-experimental failed :(
            https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli/tasks/cleanup-integration.yml
      params:
        CF_INT_DOCKER_IMAGE: {{dockerhub-private-image}}
        CF_INT_DOCKER_USERNAME: {{dockerhub-username}}
        CF_INT_DOCKER_PASSWORD: {{dockerhub-password}}
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lite-lock

- name: create-installers
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [integration-linux, integration-windows, integration-experimental]
    - get: cf-cli-binaries
      passed: [integration-linux, integration-windows, integration-experimental]
      trigger: true
    - get: cli-ci
  - task: extract-binaries
    file: cli-ci/ci/cli/tasks/extract-binaries.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-eng'
         text: "extracting the binaries in installer creation failed :("
  - aggregate:
    - task: unix
      file: cli-ci/ci/cli/tasks/create-installers.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: "create unix installers failed :("
    - task: windows
      file: cli-ci/ci/cli/tasks/create-installers-windows.yml
      on_failure:
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: "create windows installer failed :("
  - task: package-binaries
    file: cli-ci/ci/cli/tasks/package-binaries.yml
    on_failure:
       put: slack-alert
       params:
         channel: '#cli-eng'
         text: "extracting the binaries in installer creation failed :("
  - aggregate:
    - put: edge-linux-binary-32
      params:
        file: archives/cf-cli_edge_linux_i686.tgz
    - put: edge-linux-binary-64
      params:
        file: archives/cf-cli_edge_linux_x86-64.tgz
    - put: edge-osx-binary-64
      params:
        file: archives/cf-cli_edge_osx.tgz
    - put: edge-windows-binary-32
      params:
        file: archives/cf-cli_edge_win32.zip
    - put: edge-windows-binary-64
      params:
        file: archives/cf-cli_edge_winx64.zip
    - put: edge-deb-installer-32
      params:
        file: archives/cf-cli-installer_i686.deb
    - put: edge-deb-installer-64
      params:
        file: archives/cf-cli-installer_x86-64.deb
    - put: edge-redhat-installer-32
      params:
        file: archives/cf-cli-installer_i686.rpm
    - put: edge-redhat-installer-64
      params:
        file: archives/cf-cli-installer_x86-64.rpm
    - put: edge-osx-installer-64
      params:
        file: archives/cf-cli-installer_osx.pkg
    - put: edge-windows-installer-32
      params:
        file: winstallers/cf-cli-installer_win32.zip
    - put: edge-windows-installer-64
      params:
        file: winstallers/cf-cli-installer_winx64.zip
    - put: cf-cli-tracker
      params:
        repos:
        - cli

- name: cats
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [integration-linux, integration-windows, integration-experimental]
    - get: cf-acceptance-tests
    - get: cf-cli-binaries
      passed: [integration-linux, integration-windows, integration-experimental]
      trigger: true
    - get: cli-ci
    - get: vars-store
    - put: bosh-lite-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      file: cli-ci/ci/cli/tasks/cleanup-integration.yml
    - task: config
      file: cli-ci/ci/cli/tasks/cats-config.yml
      params:
        INCLUDE_V3: false
        BROKER_START_TIMEOUT: 330
        CF_PUSH_TIMEOUT: 210
        DEFAULT_TIMEOUT: 60
        LONG_CURL_TIMEOUT: 210
    - task: linux
      file: cli-ci/ci/cli/tasks/cats-linux.yml
      params:
        BACKEND: diego
        NODES: 16
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-eng'
          text: |
            CATs Linux failed :(
            https://wings.concourse.ci/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lite-lock


- name: create-cli-base-image
  serial: true
  plan:
  - aggregate:
    - get: cli-ci-base-dockerfile
      trigger: true
    - get: golang
      trigger: true
      params: {save: true}
  - put: cf-cli-base-image
    params:
      load_base: golang
      build: cli-ci-base-dockerfile/ci/cli-base

- name: create-cli-package-image
  serial: true
  plan:
  - aggregate:
    - get: cli-ci-package-dockerfile
      trigger: true
    - get: baseimage
      trigger: true
      params: {save: true}
  - put: cf-cli-package-image
    params:
      load_base: baseimage
      build: cli-ci-package-dockerfile/ci/cli-package
