---
groups:
- name: create
  jobs:
  - setup-infrastructure
  - deploy-cf
- name: delete
  jobs:
  - delete-cf
  - delete-infrastructure

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: master
- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    path: ci
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master
- name: ops-files
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master
- name: state
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: {{cli-private-github-private-key-write}}
    branch: master
    paths:
    - ci/infrastructure/hardknox/bbl-state.json
- name: cf-state
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: {{cli-private-github-private-key-write}}
    branch: master
    paths:
    - ci/infrastructure/hardknox/deployment-vars.yml

jobs:
- name: setup-infrastructure
  serial_groups: [hardknox]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: state
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-state: state
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{google_account_creds}}
      BBL_GCP_PROJECT_ID: {{gcp_project}}
      BBL_GCP_REGION: us-central1
      BBL_GCP_ZONE: us-central1-f
      BBL_LB_CERT: {{hardknox_cf_ssl_cert}}
      BBL_LB_KEY: {{hardknox_cf_ssl_cert_private_key}}
      LB_DOMAIN: hardknox.cli.fun
      BBL_ENV_NAME: hardknox
      BBL_STATE_DIR: ci/infrastructure/hardknox
    ensure:
      put: state
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-cf
  serial_groups: [hardknox]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: state
      passed: [setup-infrastructure]
      trigger: true
    - get: cf-state
    - get: cf-deployment
    - get: ops-files
    - get: cli-ci
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      bbl-state: state
    params:
      INFRASTRUCTURE: google
      BBL_STATE_DIR: ci/infrastructure/hardknox
  - task: copy-ops-files
    file: cli-ci/ci/infrastructure/tasks/combine-inputs.yml
    input_mapping:
      input1: ops-files
      input2: cli-ci
    params:
      COPY_PATHS: "input1/operations/scale-to-one-az.yml input1/operations/tcp-routing-gcp.yml input1/operations/test/add-persistent-isolation-segment-diego-cell.yml input2/ci/infrastructure/operations/cli-isolation-cell-overrides.yml input2/ci/infrastructure/operations/default-app-memory.yml input2/ci/infrastructure/operations/diego-cell-instances.yml input2/ci/infrastructure/operations/skip-ssl-override.yml"
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: state
      vars-store: cf-state
      vars-files: cf-state
      ops-files: combine_inputs_output
    params:
      SYSTEM_DOMAIN: hardknox.cli.fun
      OPS_FILES: "tcp-routing-gcp.yml add-persistent-isolation-segment-diego-cell.yml cli-isolation-cell-overrides.yml default-app-memory.yml skip-ssl-override.yml scale-to-one-az.yml diego-cell-instances.yml"
      VARS_STORE_FILE: ci/infrastructure/hardknox/deployment-vars.yml
      BBL_STATE_DIR: ci/infrastructure/hardknox
    ensure:
      put: cf-state
      params:
        repository: updated-vars-store
        rebase: true

- name: delete-cf
  serial_groups: [hardknox]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: state
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: state
    params:
      BBL_STATE_DIR: ci/infrastructure/hardknox

- name: delete-infrastructure
  serial_groups: [hardknox]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: state
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: state
    params:
      BBL_STATE_DIR: ci/infrastructure/hardknox
    ensure:
      put: state
      params:
        repository: updated-bbl-state
        rebase: true
