package internal

// When adding a resource, also add it to the api/cloudcontroller/ccv3/ccv3_suite_test.go resources response
const (
	AppsResource                      = "apps"
	BuildpacksResource                = "buildpacks"
	BuildsResource                    = "builds"
	DeploymentsResource               = "deployments"
	DomainsResource                   = "domains"
	DropletsResource                  = "droplets"
	EnvironmentVariableGroupsResource = "environment_variable_groups"
	EventsResource                    = "audit_events"
	FeatureFlagsResource              = "feature_flags"
	IsolationSegmentsResource         = "isolation_segments"
	OrgQuotasResource                 = "organization_quotas"
	OrgsResource                      = "organizations"
	PackagesResource                  = "packages"
	ProcessesResource                 = "processes"
	ResourceMatches                   = "resource_matches"
	RevisionsResource                 = "revisions"
	RolesResource                     = "roles"
	RoutesResource                    = "routes"
	SecurityGroupsResource            = "security_groups"
	ServiceBrokersResource            = "service_brokers"
	ServiceInstancesResource          = "service_instances"
	ServiceOfferingsResource          = "service_offerings"
	ServicePlansResource              = "service_plans"
	SpaceQuotasResource               = "space_quotas"
	SpacesResource                    = "spaces"
	StacksResource                    = "stacks"
	TasksResource                     = "tasks"
	UsersResource                     = "users"
)
