#!/bin/bash

# If pushing tags skip fix committer.
grep "refs/tags/" < /dev/stdin > /dev/null
if [ "$?" -eq "0" ] ; then
  exit 0
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" == 'master' ]; then
  git fr
fi
