---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: terraform
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: ((bosh-lite-storage-bucket))
      prefix: on_demand_terraform_state_files/
      credentials: ((bosh-lite-gcp-json-key))
- name: capi-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-ci

- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment

- name: cf-deploy
  type: bosh-deployment
  source:
    skip_check: true

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    tag_filter: v*

- name: cli
  type: git
  icon: console
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master

- name: cli-i18n
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-i18n
    branch: master

- name: cf-cli-binaries
  type: s3
  icon: folder
  source:
    bucket: ((staging-bucket-name))
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: "v7/cf-cli-binaries.tgz"

- name: edge-capi-release
  type: s3
  source:
    bucket: capi-releases
    regexp: capi-(.*)-.*-.*.tgz

- name: edge-linux-binary-32
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli_edge_linux_i686.tgz
    region_name: us-west-1

- name: edge-linux-binary-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli_edge_linux_x86-64.tgz
    region_name: us-west-1

- name: edge-osx-binary-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli_edge_osx.tgz
    region_name: us-west-1

- name: edge-windows-binary-32
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-binary-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli_edge_winx64.zip
    region_name: us-west-1

- name: edge-deb-installer-32
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_i686.deb
    region_name: us-west-1

- name: edge-deb-installer-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_x86-64.deb
    region_name: us-west-1

- name: edge-redhat-installer-32
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_i686.rpm
    region_name: us-west-1

- name: edge-redhat-installer-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_x86-64.rpm
    region_name: us-west-1

- name: edge-osx-installer-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_osx.pkg
    region_name: us-west-1

- name: edge-windows-installer-32
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_win32.zip
    region_name: us-west-1

- name: edge-windows-installer-64
  type: s3
  source:
    bucket: v7-cf-cli-releases
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: master/cf7-cli-installer_edge_winx64.zip
    region_name: us-west-1

- name: gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((cli-pools-github-private-key))
    branch: master
    pool: mashed-potato

- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: ((vat-slack-webhook-url))

- name: vars-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: ((cli-private-github-private-key))
    branch: master

# values for this already exist in last pass, blocked on
# blocked on https://github.com/concourse/concourse/issues/1407
- name: cf-cli-tracker
  type: tracker
  source:
    token: ((cf-cli-public-tracker-token))
    project_id: '2196383'
    tracker_url: https://www.pivotaltracker.com

jobs:
- name: units
  serial: true
  plan:
  - in_parallel:
    - get: cli
      trigger: true
  - in_parallel:
    - task: lint
      file: cli/ci/cli-v7/tasks/lint.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: &slack_notification_text |
            $BUILD_JOB_NAME failed :(
            $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME - (Viewable internally only)
    - task: units-linux
      file: cli/ci/cli-v7/tasks/units-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
    - task: units-osx
      file: cli/ci/cli-v7/tasks/units-osx.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
    - task: units-windows
      tags: [vat-windows]
      file: cli/ci/cli-v7/tasks/units-windows.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text

- name: build-binaries
  serial: true
  plan:
  - in_parallel:
    - get: cli
      trigger: true
      passed: [units]
    - get: cli-i18n
  - task: build-i18n
    file: cli/ci/cli-v7/tasks/generate-i18n-resources.yml
    on_failure:
      put: slack-alert
      params:
        channel: '#v3-acceleration-team'
        text: *slack_notification_text
  - in_parallel:
    - task: build
      file: cli/ci/cli-v7/tasks/build-binaries.yml
      params:
        TARGET_GO_VERSION: go1.13.4
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
    - task: build-osx
      file: cli/ci/cli-v7/tasks/build-osx-binary.yml
      params:
        TARGET_GO_VERSION: go1.13.4
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
  - task: combine-binaries
    file: cli/ci/cli-v7/tasks/combine-binaries.yml
  - put: cf-cli-binaries
    params:
      file: compiled/cf-cli-binaries.tgz

- name: integration-linux
  serial: true
  plan:
  - in_parallel: &integration_resources
    - get: cli
      passed: [build-binaries]
    - get: cf-cli-binaries
      passed: [build-binaries]
      trigger: true
    - get: vars-store
    - put: bosh-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      file: cli/ci/cli-v7/tasks/cleanup-integration.yml
    - task: integration
      file: cli/ci/cli-v7/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli/ci/cli-v7/tasks/cleanup-integration.yml
      params: &integration_params
        CF_INT_CLIENT_ID: 'potato-face'
        CF_INT_CLIENT_SECRET: ((client-secret))
        CF_INT_DOCKER_IMAGE: ((dockerhub-private-image))
        CF_INT_DOCKER_USERNAME: ((dockerhub-username))
        CF_INT_DOCKER_PASSWORD: ((dockerhub-password))
        CF_INT_IGNORE_API_VERSION_CHECK: false
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-linux-bosh-lite
  plan:
  - in_parallel:
    - get: bosh-deployment
    - get: capi-ci
    - get: cf-deployment
    - get: cli
      passed: [build-binaries]
    - get: cf-cli-binaries
      passed: [build-binaries]
      trigger: true
    - get: edge-capi-release
    - get: vars-store
  - do:
    - put: terraform
      params:
        generate_random_name: true
        delete_on_failure: true
        terraform_source: capi-ci/terraform/bosh-lite/
        vars:
          project_id: ((bosh-lite-project-id))
          json_key: ((bosh-lite-gcp-json-key))
          dns_project_id: ((bosh-lite-project-id))
          dns_json_key: ((bosh-lite-gcp-json-key))
          system_domain_suffix: ((bosh-lite-system-domain-suffix))
          dns_zone_name: ((bosh-lite-dns-zone-name))
    - do:
        - task: create-bosh-lite
          file: capi-ci/ci/bosh-lite/create-bosh-lite.yml
          params:
            GCP_JSON_KEY: ((bosh-lite-gcp-json-key))
            GCP_INSTANCE_TYPE: n1-highmem-16
        - do:
            - task: create-env-vars-file
              file: capi-ci/ci/bosh-lite/create-env-vars-file.yml
            - task: upload-cf-assets
              file: capi-ci/ci/bosh-lite/upload-cf-assets.yml
            - task: write-bosh-target-file
              file: capi-ci/ci/bosh-lite/write-bosh-target-file.yml
            - put: cf-deploy
              params:
                source_file: bosh-target/target.yml
                manifest: cf-deployment/cf-deployment.yml
                vars_files:
                - bosh-target/vars.yml
                var_files:
                  edge_capi_url: edge-capi-release/url
                vars:
                  client-secret: ((client-secret))
                ops_files:
                - capi-ci/cf-deployment-operations/skip-cert-verify.yml
                - capi-ci/cf-deployment-operations/use-latest-stemcell.yml
                - cf-deployment/operations/bosh-lite.yml
                - cf-deployment/operations/use-compiled-releases.yml
                - cf-deployment/operations/test/add-persistent-isolation-segment-diego-cell.yml
                - cf-deployment/operations/test/add-persistent-isolation-segment-diego-cell-bosh-lite.yml
                - cf-deployment/operations/use-internal-lookup-for-route-services.yml
                - capi-ci/cf-deployment-operations/seed-credhub-asg.yml
                - cli/ci/infrastructure/operations/default-app-memory.yml
                - cli/ci/infrastructure/operations/add-oidc-provider.yml
                - cli/ci/infrastructure/operations/add-uaa-client-cf-custom.yml
                - cli/ci/infrastructure/operations/give-cf-admin-clients-read-scope.yml
                - cli/ci/infrastructure/operations/use-edge-capi.yml
                - cli/ci/infrastructure/operations/add-uaa-client-credentials.yml
            - task: upload-to-gcs
              file: capi-ci/ci/gcs/upload-to-gcs.yml
              input_mapping:
                environment: terraform
                source-directory: director-state
              params:
                GCP_JSON_KEY: ((bosh-lite-gcp-json-key))
                GCP_BUCKET: ((bosh-lite-storage-bucket))
                GCP_PATH: director-state
                USE_ENV_NAMED_SUBDIR: true
          on_failure:
            task: delete-bosh-lite
            file: capi-ci/ci/bosh-lite/delete-bosh-lite.yml
      on_failure:
        put: terraform
        params:
          action: destroy
          env_name_file: terraform/name
          terraform_source: capi-ci/terraform/bosh-lite/
          vars:
            project_id: ((bosh-lite-project-id))
            json_key: ((bosh-lite-gcp-json-key))
            dns_project_id: ((bosh-lite-project-id))
            dns_json_key: ((bosh-lite-gcp-json-key))
            system_domain_suffix: ((bosh-lite-system-domain-suffix))
            dns_zone_name: ((bosh-lite-dns-zone-name))
        get_params:
          action: destroy
  - do:
    - task: integration
      file: cli/ci/cli-v7/tasks/integration-linux-bosh-lite.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
      params: *integration_params
    ensure:
      do:
        - task: delete-bosh-lite
          file: capi-ci/ci/bosh-lite/delete-bosh-lite.yml
        - put: terraform
          params:
            action: destroy
            env_name_file: terraform/name
            terraform_source: capi-ci/terraform/bosh-lite/
            vars:
              project_id: ((bosh-lite-project-id))
              json_key: ((bosh-lite-gcp-json-key))
              dns_project_id: ((bosh-lite-project-id))
              dns_json_key: ((bosh-lite-gcp-json-key))
              system_domain_suffix: ((bosh-lite-system-domain-suffix))
              dns_zone_name: ((bosh-lite-dns-zone-name))
          get_params:
            action: destroy
- name: integration-linux-client-creds
  serial: true
  plan:
  - in_parallel: *integration_resources
  - do:
    - task: cleanup-integration
      file: cli/ci/cli-v7/tasks/cleanup-integration.yml
    - task: integration
      file: cli/ci/cli-v7/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli/ci/cli-v7/tasks/cleanup-integration.yml
      params:
        <<: *integration_params
        CF_INT_CLIENT_CREDENTIALS_TEST_MODE: true
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-windows
  serial: true
  plan:
  - in_parallel: *integration_resources
  - do:
    - task: cleanup-integration
      file: cli/ci/cli-v7/tasks/cleanup-integration.yml
    - task: integration
      tags: [vat-windows]
      file: cli/ci/cli-v7/tasks/integration-windows.yml
      params:
        <<: *integration_params
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli/ci/cli-v7/tasks/cleanup-integration.yml
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-windows-client-creds
  serial: true
  plan:
  - in_parallel: *integration_resources
  - do:
    - task: cleanup-integration
      file: cli/ci/cli-v7/tasks/cleanup-integration.yml
    - task: integration
      tags: [vat-windows]
      file: cli/ci/cli-v7/tasks/integration-windows.yml
      params:
        <<: *integration_params
        CF_INT_CLIENT_CREDENTIALS_TEST_MODE: true
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli/ci/cli-v7/tasks/cleanup-integration.yml
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: create-installers
  serial: true
  plan:
  - in_parallel:
    - get: cli
      passed:
      - integration-linux
      - integration-linux-client-creds
      - integration-windows
      - integration-windows-client-creds
    - get: cf-cli-binaries
      passed:
      - integration-linux
      - integration-linux-client-creds
      - integration-windows
      - integration-windows-client-creds
      trigger: true
  - task: extract-binaries
    file: cli/ci/cli-v7/tasks/extract-binaries.yml
    on_failure:
      put: slack-alert
      params:
        channel: '#v3-acceleration-team'
        text: |
          extracting the binaries in installer creation failed :bart:
          $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - in_parallel:
    - task: unix
      file: cli/ci/cli-v7/tasks/create-installers.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: |
            :ubuntu: create unix installers failed :redhat:
            $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    - task: windows
      tags: [vat-windows]
      file: cli/ci/cli-v7/tasks/create-installers-windows.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#v3-acceleration-team'
          text: |
            create windows installer failed :winc:
            $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - task: package-binaries
    file: cli/ci/cli-v7/tasks/package-binaries.yml
    on_failure:
      put: slack-alert
      params:
        channel: '#v3-acceleration-team'
        text: |
          extracting the binaries in installer creation failed :package:
          $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - in_parallel:
    - put: edge-linux-binary-32
      params:
        file: archives/cf7-cli_edge_linux_i686.tgz
    - put: edge-linux-binary-64
      params:
        file: archives/cf7-cli_edge_linux_x86-64.tgz
    - put: edge-osx-binary-64
      params:
        file: archives/cf7-cli_edge_osx.tgz
    - put: edge-windows-binary-32
      params:
        file: archives/cf7-cli_edge_win32.zip
    - put: edge-windows-binary-64
      params:
        file: archives/cf7-cli_edge_winx64.zip
    - put: edge-deb-installer-32
      params:
        file: archives/cf7-cli-installer_i686.deb
    - put: edge-deb-installer-64
      params:
        file: archives/cf7-cli-installer_x86-64.deb
    - put: edge-redhat-installer-32
      params:
        file: archives/cf7-cli-installer_i686.rpm
    - put: edge-redhat-installer-64
      params:
        file: archives/cf7-cli-installer_x86-64.rpm
    - put: edge-osx-installer-64
      params:
        file: archives/cf7-cli-installer_osx.pkg
    - put: edge-windows-installer-32
      params:
        file: winstallers/cf7-cli-installer_win32.zip
    - put: edge-windows-installer-64
      params:
        file: winstallers/cf7-cli-installer_winx64.zip

- name: deliver-stories
  serial: true
  plan:
  - get: cli
    passed:
    - integration-linux
    - integration-windows
    - integration-linux-client-creds
    - integration-windows-client-creds
    trigger: true
  - put: cf-cli-tracker
    params:
      repos:
      - cli
