name: Unclaim an environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      identifier-for-metadata-file:
        required: true
        type: string

jobs:
  build-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download metadata
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.identifier-for-metadata-file }}

      - name: Unclaim environment
        run: |
          curl -X POST "https://environments.toolsmiths.cf-app.com/pooled_gcp_engineering_environments/unclaim?api_token=${{ secrets.TOOLSMITHS_API_TOKEN }}&name=$(cat metadata.json | jq -r .name)"