#!/bin/bash
set -e

chmod +x out/cf-darwin-amd64
chmod +x out/cf-linux-386
chmod +x out/cf-linux-amd64
chmod +x out/cf-windows-amd64.exe
chmod +x out/cf-windows-386.exe

ci/scripts/build-installers-gocd
ci/scripts/tar-executables
ci/scripts/upload-binaries-gocd

#( /bin/bash --login -c "rvm use 1.9 && bin/pivotal-tracker-deliver"; exit 0 )
