#!/bin/bash
set -ex

chmod +x out/cf-cli*

ci/scripts/build-installers-gocd
ci/scripts/tar-executables
ci/scripts/upload-binaries-gocd

#( /bin/bash --login -c "rvm use 1.9 && bin/pivotal-tracker-deliver"; exit 0 )
