#!/usr/bin/env bash

set -e

export GOPATH=~/go
export CATSPATH=$GOPATH/src/github.com/cloudfoundry/cf-acceptance-tests

curl https://s3.amazonaws.com/go-cli/builds/cf-linux-amd64 > $CATSPATH/gcf

export PATH=$PATH:$CATSPATH

cd $CATSPATH
$GOPATH/bin/ginkgo -r -v -slowSpecThreshold=300 -skip="admin buildpack"
