---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
- name: bosh-lite-pool
  type: docker-image
  source:
    repository: cfcli/pr-pool-manager
    tag: latest

resources:
- name: cli
  type: pull-request
  check_every: 1m
  source:
    disable_forks: true
    repository: cloudfoundry/cli
    access_token: ((github-access-token))
    # base: master # Only build PRs that want to merge to master
    # disable_forks: true # Until we're sure of the security, only build PRs on the main repo, so that only people with push access can trigger
    # only_mergeable: true # Don't spend resources building PRs that can't be merged.
    ignore_paths:
    - README.md
    - .github/

- name: bosh-lite
  type: bosh-lite-pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((cli-pools-github-private-key))
    branch: master
    pool: bosh-lites

# - name: legacy-gcp-bosh-pool
#   type: pool
#   source:
#     uri: git@github.com:cloudfoundry/cli-pools
#     private_key: ((cli-pools-github-private-key))
#     branch: master
#     pool: moldy-gnocchi

# - name: golang
#   type: docker-image
#   source:
#     repository: golang
#     tag: 1.11

groups:
- name: cli
  jobs:
  - units
  - claim-bosh-lite
  - integration-linux

jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
  - aggregate:
    - task: units-linux
      timeout: 30m
      file: cli/ci/cli/tasks/units-linux.yml

- name: claim-bosh-lite # TODO: record PR number instead of usernames
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      version: every
      passed: [units]
  - do:
    - task: get-pr-info
      file: cli/ci/cli-pr-builder/tasks/extract-info-from-pr.yml
    - put: bosh-lite
      params:
        story: commit-info/pr-id
        author_name: commit-info/author-name
        author_email: commit-info/author-email
        committer_name: commit-info/committer-name
        committer_email: commit-info/committer-email
        commit_message_prefix: CLI-PR-BUILDER-

- name: integration-linux # TODO: clean this up
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
      passed: [claim-bosh-lite]
      version: every
    - get: bosh-lite
      passed: [claim-bosh-lite]
      version: every
  - do:
    - task: integration
      file: cli/ci/cli-pr-builder/tasks/integration-linux.yml
      timeout: 1h30m
      params:
        CF_INT_IGNORE_API_VERSION_CHECK: false
      on_failure:
        put: cli
        params:
          path: cli
          status: failure
      ensure:
        put: unclaim-bosh-lite
        resource: bosh-lite
        params:
          operation: unclaim
          name: bosh-lite/name
    - put: cli
      params:
        path: cli
        status: success
