---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: input1
  - name: input2

outputs:
  - name: combine_inputs_output

params:
  COPY_PATHS:

run:
  path: sh
  args:
  - -c
  - |
    set -eux

    cp -r $COPY_PATHS combine_inputs_output
