---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/provision-bosh-lite

params:
  BOSH_LITE_NAME:
  BOSH_AWS_ACCESS_KEY_ID:
  BOSH_AWS_SECRET_ACCESS_KEY:
  BOSH_LITE_ELASTIC_IP:
  BOSH_LITE_KEYPAIR:
  BOSH_LITE_SECURITY_GROUP:
  BOSH_LITE_SUBNET_ID:
  LITE_PRIVATE_KEY:
  BOSH_LITE_INSTANCE_TYPE: m3.2xlarge

inputs:
  - name: bosh-lite

run:
  path: bash
  args:
  - -c
  - |
    set -e

    echo "$LITE_PRIVATE_KEY" > bosh-lite-private-key
    export BOSH_LITE_PRIVATE_KEY=$PWD/bosh-lite-private-key

    pushd bosh-lite
      vagrant up --provider aws --destroy-on-error
    popd
