// Code generated by counterfeiter. DO NOT EDIT.
package v3fakes

import (
	"sync"

	"code.cloudfoundry.org/cli/actor/v3action"
	"code.cloudfoundry.org/cli/command/v3"
)

type FakeV3AppsActor struct {
	CloudControllerAPIVersionStub        func() string
	cloudControllerAPIVersionMutex       sync.RWMutex
	cloudControllerAPIVersionArgsForCall []struct{}
	cloudControllerAPIVersionReturns     struct {
		result1 string
	}
	cloudControllerAPIVersionReturnsOnCall map[int]struct {
		result1 string
	}
	GetApplicationsWithProcessesBySpaceStub        func(spaceGUID string) ([]v3action.ApplicationWithProcessSummary, v3action.Warnings, error)
	getApplicationsWithProcessesBySpaceMutex       sync.RWMutex
	getApplicationsWithProcessesBySpaceArgsForCall []struct {
		spaceGUID string
	}
	getApplicationsWithProcessesBySpaceReturns struct {
		result1 []v3action.ApplicationWithProcessSummary
		result2 v3action.Warnings
		result3 error
	}
	getApplicationsWithProcessesBySpaceReturnsOnCall map[int]struct {
		result1 []v3action.ApplicationWithProcessSummary
		result2 v3action.Warnings
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeV3AppsActor) CloudControllerAPIVersion() string {
	fake.cloudControllerAPIVersionMutex.Lock()
	ret, specificReturn := fake.cloudControllerAPIVersionReturnsOnCall[len(fake.cloudControllerAPIVersionArgsForCall)]
	fake.cloudControllerAPIVersionArgsForCall = append(fake.cloudControllerAPIVersionArgsForCall, struct{}{})
	fake.recordInvocation("CloudControllerAPIVersion", []interface{}{})
	fake.cloudControllerAPIVersionMutex.Unlock()
	if fake.CloudControllerAPIVersionStub != nil {
		return fake.CloudControllerAPIVersionStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.cloudControllerAPIVersionReturns.result1
}

func (fake *FakeV3AppsActor) CloudControllerAPIVersionCallCount() int {
	fake.cloudControllerAPIVersionMutex.RLock()
	defer fake.cloudControllerAPIVersionMutex.RUnlock()
	return len(fake.cloudControllerAPIVersionArgsForCall)
}

func (fake *FakeV3AppsActor) CloudControllerAPIVersionReturns(result1 string) {
	fake.CloudControllerAPIVersionStub = nil
	fake.cloudControllerAPIVersionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeV3AppsActor) CloudControllerAPIVersionReturnsOnCall(i int, result1 string) {
	fake.CloudControllerAPIVersionStub = nil
	if fake.cloudControllerAPIVersionReturnsOnCall == nil {
		fake.cloudControllerAPIVersionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.cloudControllerAPIVersionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeV3AppsActor) GetApplicationsWithProcessesBySpace(spaceGUID string) ([]v3action.ApplicationWithProcessSummary, v3action.Warnings, error) {
	fake.getApplicationsWithProcessesBySpaceMutex.Lock()
	ret, specificReturn := fake.getApplicationsWithProcessesBySpaceReturnsOnCall[len(fake.getApplicationsWithProcessesBySpaceArgsForCall)]
	fake.getApplicationsWithProcessesBySpaceArgsForCall = append(fake.getApplicationsWithProcessesBySpaceArgsForCall, struct {
		spaceGUID string
	}{spaceGUID})
	fake.recordInvocation("GetApplicationsWithProcessesBySpace", []interface{}{spaceGUID})
	fake.getApplicationsWithProcessesBySpaceMutex.Unlock()
	if fake.GetApplicationsWithProcessesBySpaceStub != nil {
		return fake.GetApplicationsWithProcessesBySpaceStub(spaceGUID)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.getApplicationsWithProcessesBySpaceReturns.result1, fake.getApplicationsWithProcessesBySpaceReturns.result2, fake.getApplicationsWithProcessesBySpaceReturns.result3
}

func (fake *FakeV3AppsActor) GetApplicationsWithProcessesBySpaceCallCount() int {
	fake.getApplicationsWithProcessesBySpaceMutex.RLock()
	defer fake.getApplicationsWithProcessesBySpaceMutex.RUnlock()
	return len(fake.getApplicationsWithProcessesBySpaceArgsForCall)
}

func (fake *FakeV3AppsActor) GetApplicationsWithProcessesBySpaceArgsForCall(i int) string {
	fake.getApplicationsWithProcessesBySpaceMutex.RLock()
	defer fake.getApplicationsWithProcessesBySpaceMutex.RUnlock()
	return fake.getApplicationsWithProcessesBySpaceArgsForCall[i].spaceGUID
}

func (fake *FakeV3AppsActor) GetApplicationsWithProcessesBySpaceReturns(result1 []v3action.ApplicationWithProcessSummary, result2 v3action.Warnings, result3 error) {
	fake.GetApplicationsWithProcessesBySpaceStub = nil
	fake.getApplicationsWithProcessesBySpaceReturns = struct {
		result1 []v3action.ApplicationWithProcessSummary
		result2 v3action.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeV3AppsActor) GetApplicationsWithProcessesBySpaceReturnsOnCall(i int, result1 []v3action.ApplicationWithProcessSummary, result2 v3action.Warnings, result3 error) {
	fake.GetApplicationsWithProcessesBySpaceStub = nil
	if fake.getApplicationsWithProcessesBySpaceReturnsOnCall == nil {
		fake.getApplicationsWithProcessesBySpaceReturnsOnCall = make(map[int]struct {
			result1 []v3action.ApplicationWithProcessSummary
			result2 v3action.Warnings
			result3 error
		})
	}
	fake.getApplicationsWithProcessesBySpaceReturnsOnCall[i] = struct {
		result1 []v3action.ApplicationWithProcessSummary
		result2 v3action.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeV3AppsActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cloudControllerAPIVersionMutex.RLock()
	defer fake.cloudControllerAPIVersionMutex.RUnlock()
	fake.getApplicationsWithProcessesBySpaceMutex.RLock()
	defer fake.getApplicationsWithProcessesBySpaceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeV3AppsActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v3.V3AppsActor = new(FakeV3AppsActor)
