// Code generated by counterfeiter. DO NOT EDIT.
package v3fakes

import (
	"sync"

	"code.cloudfoundry.org/cli/actor/cfnetworkingaction"
	"code.cloudfoundry.org/cli/command/v3"
)

type FakeRemoveNetworkPolicyActor struct {
	RemoveNetworkPolicyStub        func(spaceGUID string, srcAppName string, destAppName string, protocol string, startPort int, endPort int) (cfnetworkingaction.Warnings, error)
	removeNetworkPolicyMutex       sync.RWMutex
	removeNetworkPolicyArgsForCall []struct {
		spaceGUID   string
		srcAppName  string
		destAppName string
		protocol    string
		startPort   int
		endPort     int
	}
	removeNetworkPolicyReturns struct {
		result1 cfnetworkingaction.Warnings
		result2 error
	}
	removeNetworkPolicyReturnsOnCall map[int]struct {
		result1 cfnetworkingaction.Warnings
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRemoveNetworkPolicyActor) RemoveNetworkPolicy(spaceGUID string, srcAppName string, destAppName string, protocol string, startPort int, endPort int) (cfnetworkingaction.Warnings, error) {
	fake.removeNetworkPolicyMutex.Lock()
	ret, specificReturn := fake.removeNetworkPolicyReturnsOnCall[len(fake.removeNetworkPolicyArgsForCall)]
	fake.removeNetworkPolicyArgsForCall = append(fake.removeNetworkPolicyArgsForCall, struct {
		spaceGUID   string
		srcAppName  string
		destAppName string
		protocol    string
		startPort   int
		endPort     int
	}{spaceGUID, srcAppName, destAppName, protocol, startPort, endPort})
	fake.recordInvocation("RemoveNetworkPolicy", []interface{}{spaceGUID, srcAppName, destAppName, protocol, startPort, endPort})
	fake.removeNetworkPolicyMutex.Unlock()
	if fake.RemoveNetworkPolicyStub != nil {
		return fake.RemoveNetworkPolicyStub(spaceGUID, srcAppName, destAppName, protocol, startPort, endPort)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.removeNetworkPolicyReturns.result1, fake.removeNetworkPolicyReturns.result2
}

func (fake *FakeRemoveNetworkPolicyActor) RemoveNetworkPolicyCallCount() int {
	fake.removeNetworkPolicyMutex.RLock()
	defer fake.removeNetworkPolicyMutex.RUnlock()
	return len(fake.removeNetworkPolicyArgsForCall)
}

func (fake *FakeRemoveNetworkPolicyActor) RemoveNetworkPolicyArgsForCall(i int) (string, string, string, string, int, int) {
	fake.removeNetworkPolicyMutex.RLock()
	defer fake.removeNetworkPolicyMutex.RUnlock()
	return fake.removeNetworkPolicyArgsForCall[i].spaceGUID, fake.removeNetworkPolicyArgsForCall[i].srcAppName, fake.removeNetworkPolicyArgsForCall[i].destAppName, fake.removeNetworkPolicyArgsForCall[i].protocol, fake.removeNetworkPolicyArgsForCall[i].startPort, fake.removeNetworkPolicyArgsForCall[i].endPort
}

func (fake *FakeRemoveNetworkPolicyActor) RemoveNetworkPolicyReturns(result1 cfnetworkingaction.Warnings, result2 error) {
	fake.RemoveNetworkPolicyStub = nil
	fake.removeNetworkPolicyReturns = struct {
		result1 cfnetworkingaction.Warnings
		result2 error
	}{result1, result2}
}

func (fake *FakeRemoveNetworkPolicyActor) RemoveNetworkPolicyReturnsOnCall(i int, result1 cfnetworkingaction.Warnings, result2 error) {
	fake.RemoveNetworkPolicyStub = nil
	if fake.removeNetworkPolicyReturnsOnCall == nil {
		fake.removeNetworkPolicyReturnsOnCall = make(map[int]struct {
			result1 cfnetworkingaction.Warnings
			result2 error
		})
	}
	fake.removeNetworkPolicyReturnsOnCall[i] = struct {
		result1 cfnetworkingaction.Warnings
		result2 error
	}{result1, result2}
}

func (fake *FakeRemoveNetworkPolicyActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.removeNetworkPolicyMutex.RLock()
	defer fake.removeNetworkPolicyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRemoveNetworkPolicyActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v3.RemoveNetworkPolicyActor = new(FakeRemoveNetworkPolicyActor)
