---
- type: replace
  path: /instance_groups/name=diego-cell/instances
  value: 4

- type: replace
  path: /instance_groups/name=isolated-diego-cell/jobs/name=rep/properties?/set_kernel_parameters
  value: false
