// This file was generated by counterfeiter
package coreconfigfakes

import (
	"sync"

	"github.com/cloudfoundry/cli/cf/configuration/coreconfig"
)

type FakeEndpointRepository struct {
	GetCCInfoStub        func(string) (*coreconfig.CCInfo, string, error)
	getCCInfoMutex       sync.RWMutex
	getCCInfoArgsForCall []struct {
		arg1 string
	}
	getCCInfoReturns struct {
		result1 *coreconfig.CCInfo
		result2 string
		result3 error
	}
}

func (fake *FakeEndpointRepository) GetCCInfo(arg1 string) (*coreconfig.CCInfo, string, error) {
	fake.getCCInfoMutex.Lock()
	fake.getCCInfoArgsForCall = append(fake.getCCInfoArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.getCCInfoMutex.Unlock()
	if fake.GetCCInfoStub != nil {
		return fake.GetCCInfoStub(arg1)
	} else {
		return fake.getCCInfoReturns.result1, fake.getCCInfoReturns.result2, fake.getCCInfoReturns.result3
	}
}

func (fake *FakeEndpointRepository) GetCCInfoCallCount() int {
	fake.getCCInfoMutex.RLock()
	defer fake.getCCInfoMutex.RUnlock()
	return len(fake.getCCInfoArgsForCall)
}

func (fake *FakeEndpointRepository) GetCCInfoArgsForCall(i int) string {
	fake.getCCInfoMutex.RLock()
	defer fake.getCCInfoMutex.RUnlock()
	return fake.getCCInfoArgsForCall[i].arg1
}

func (fake *FakeEndpointRepository) GetCCInfoReturns(result1 *coreconfig.CCInfo, result2 string, result3 error) {
	fake.GetCCInfoStub = nil
	fake.getCCInfoReturns = struct {
		result1 *coreconfig.CCInfo
		result2 string
		result3 error
	}{result1, result2, result3}
}

var _ coreconfig.EndpointRepository = new(FakeEndpointRepository)
