// Code generated by counterfeiter. DO NOT EDIT.
package v2fakes

import (
	"sync"

	"code.cloudfoundry.org/cli/actor/v2action"
	"code.cloudfoundry.org/cli/command/v2"
	"code.cloudfoundry.org/cli/util/progressbar"
)

type FakeCreateBuildpackActor struct {
	CreateBuildpackStub        func(name string, position int, enabled bool) (v2action.Buildpack, v2action.Warnings, error)
	createBuildpackMutex       sync.RWMutex
	createBuildpackArgsForCall []struct {
		name     string
		position int
		enabled  bool
	}
	createBuildpackReturns struct {
		result1 v2action.Buildpack
		result2 v2action.Warnings
		result3 error
	}
	createBuildpackReturnsOnCall map[int]struct {
		result1 v2action.Buildpack
		result2 v2action.Warnings
		result3 error
	}
	UploadBuildpackStub        func(GUID string, path string, pb progressbar.ProgressBar) (v2action.Warnings, error)
	uploadBuildpackMutex       sync.RWMutex
	uploadBuildpackArgsForCall []struct {
		GUID string
		path string
		pb   progressbar.ProgressBar
	}
	uploadBuildpackReturns struct {
		result1 v2action.Warnings
		result2 error
	}
	uploadBuildpackReturnsOnCall map[int]struct {
		result1 v2action.Warnings
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateBuildpackActor) CreateBuildpack(name string, position int, enabled bool) (v2action.Buildpack, v2action.Warnings, error) {
	fake.createBuildpackMutex.Lock()
	ret, specificReturn := fake.createBuildpackReturnsOnCall[len(fake.createBuildpackArgsForCall)]
	fake.createBuildpackArgsForCall = append(fake.createBuildpackArgsForCall, struct {
		name     string
		position int
		enabled  bool
	}{name, position, enabled})
	fake.recordInvocation("CreateBuildpack", []interface{}{name, position, enabled})
	fake.createBuildpackMutex.Unlock()
	if fake.CreateBuildpackStub != nil {
		return fake.CreateBuildpackStub(name, position, enabled)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.createBuildpackReturns.result1, fake.createBuildpackReturns.result2, fake.createBuildpackReturns.result3
}

func (fake *FakeCreateBuildpackActor) CreateBuildpackCallCount() int {
	fake.createBuildpackMutex.RLock()
	defer fake.createBuildpackMutex.RUnlock()
	return len(fake.createBuildpackArgsForCall)
}

func (fake *FakeCreateBuildpackActor) CreateBuildpackArgsForCall(i int) (string, int, bool) {
	fake.createBuildpackMutex.RLock()
	defer fake.createBuildpackMutex.RUnlock()
	return fake.createBuildpackArgsForCall[i].name, fake.createBuildpackArgsForCall[i].position, fake.createBuildpackArgsForCall[i].enabled
}

func (fake *FakeCreateBuildpackActor) CreateBuildpackReturns(result1 v2action.Buildpack, result2 v2action.Warnings, result3 error) {
	fake.CreateBuildpackStub = nil
	fake.createBuildpackReturns = struct {
		result1 v2action.Buildpack
		result2 v2action.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCreateBuildpackActor) CreateBuildpackReturnsOnCall(i int, result1 v2action.Buildpack, result2 v2action.Warnings, result3 error) {
	fake.CreateBuildpackStub = nil
	if fake.createBuildpackReturnsOnCall == nil {
		fake.createBuildpackReturnsOnCall = make(map[int]struct {
			result1 v2action.Buildpack
			result2 v2action.Warnings
			result3 error
		})
	}
	fake.createBuildpackReturnsOnCall[i] = struct {
		result1 v2action.Buildpack
		result2 v2action.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCreateBuildpackActor) UploadBuildpack(GUID string, path string, pb progressbar.ProgressBar) (v2action.Warnings, error) {
	fake.uploadBuildpackMutex.Lock()
	ret, specificReturn := fake.uploadBuildpackReturnsOnCall[len(fake.uploadBuildpackArgsForCall)]
	fake.uploadBuildpackArgsForCall = append(fake.uploadBuildpackArgsForCall, struct {
		GUID string
		path string
		pb   progressbar.ProgressBar
	}{GUID, path, pb})
	fake.recordInvocation("UploadBuildpack", []interface{}{GUID, path, pb})
	fake.uploadBuildpackMutex.Unlock()
	if fake.UploadBuildpackStub != nil {
		return fake.UploadBuildpackStub(GUID, path, pb)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.uploadBuildpackReturns.result1, fake.uploadBuildpackReturns.result2
}

func (fake *FakeCreateBuildpackActor) UploadBuildpackCallCount() int {
	fake.uploadBuildpackMutex.RLock()
	defer fake.uploadBuildpackMutex.RUnlock()
	return len(fake.uploadBuildpackArgsForCall)
}

func (fake *FakeCreateBuildpackActor) UploadBuildpackArgsForCall(i int) (string, string, progressbar.ProgressBar) {
	fake.uploadBuildpackMutex.RLock()
	defer fake.uploadBuildpackMutex.RUnlock()
	return fake.uploadBuildpackArgsForCall[i].GUID, fake.uploadBuildpackArgsForCall[i].path, fake.uploadBuildpackArgsForCall[i].pb
}

func (fake *FakeCreateBuildpackActor) UploadBuildpackReturns(result1 v2action.Warnings, result2 error) {
	fake.UploadBuildpackStub = nil
	fake.uploadBuildpackReturns = struct {
		result1 v2action.Warnings
		result2 error
	}{result1, result2}
}

func (fake *FakeCreateBuildpackActor) UploadBuildpackReturnsOnCall(i int, result1 v2action.Warnings, result2 error) {
	fake.UploadBuildpackStub = nil
	if fake.uploadBuildpackReturnsOnCall == nil {
		fake.uploadBuildpackReturnsOnCall = make(map[int]struct {
			result1 v2action.Warnings
			result2 error
		})
	}
	fake.uploadBuildpackReturnsOnCall[i] = struct {
		result1 v2action.Warnings
		result2 error
	}{result1, result2}
}

func (fake *FakeCreateBuildpackActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createBuildpackMutex.RLock()
	defer fake.createBuildpackMutex.RUnlock()
	fake.uploadBuildpackMutex.RLock()
	defer fake.uploadBuildpackMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCreateBuildpackActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v2.CreateBuildpackActor = new(FakeCreateBuildpackActor)
