name: Remove safe-to-test label on new commits

on:
  pull_request_target:
    branches:
      - main
      - v8
    types:
      - synchronize

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - name: Remove safe-to-test label
        run: gh pr edit "${{ github.event.pull_request.number }}" --remove-label "safe-to-test"
        env:
          GH_TOKEN: ${{ github.token }}
