name: testbed

on:
  workflow_dispatch:

permissions:
  contents: read

jobs: 
  test-claim-ts:
    name: claim-${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
#           - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - id: claim-toolsmiths-env
      name: Claim Toolsmiths Environment
      env:
        api_token: ${{ secrets.TOOLSMITHS_API_TOKEN }}
        hostname:  ${{ secrets.TOOLSMITHS_HOSTNAME }}
      run: |
          set -x

          echo hostname - ${hostname}

          curl -s --show-error -H 'Accept: application/json' \
          -X GET "https://environments.toolsmiths.cf-app.com/v1/custom_gcp/cf-deployment/versions?api_token=${api_token}"

    # This is for debugging windows
    - name: enable ssh
      if: always()
      run: |
        Get-WindowsCapability -Online
        $componentName = $(Get-WindowsCapability -Online |Where-Object Name -like 'OpenSSH.Server*').Name
        Add-WindowsCapability -Online -Name $componentName
        Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP"

    - name: ssh session
      if: always()
      run: |
        Start-Service sshd
        echo "IP address below:"
        Get-NetIPAddress | Select-Object -Property IPAddress
        sleep 3600
        Stop-Service sshd
