name: test-windows-install

on:
  push:

permissions:
  contents: read

jobs: 
  test-install:
    name: install-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - windows-latest
          - windows-2019
          - macos-11
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: install
      shell: bash
      run: |
        echo ${{ matrix.foo }}
        if [[ ${{ matrix.os }} =~ "windows" ]]
        then
          install_location=/usr/bin
          bbl_artifact=bbl-v8.4.110_windows.exe
        else
          install_location=/usr/local/bin
          bbl_artifact=bbl-v8.4.110_linux_x86-64
        fi
        curl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.110/${bbl_artifact} --silent --location --output  $install_location/bbl
        echo "download worked"
        chmod +x $install_location/bbl
        bbl --version

