name: Test AWS

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    test-aws:
        # name: test
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-1
                # AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                # SOURCE_DIR: upload
                # DEST_DIR: "releases/v${{ env.INSTALLER_RELEASE_VERSION }}"
                role-to-assume: ${{ secrets.AWS_S3_ROLE_ARN }}
                role-skip-session-tagging: true
                role-duration-seconds: 1200
            
            - name: Copy files to the test website with the AWS CLI
              run: |
                  touch test.txt
                  aws s3 sync . s3://cf-cli-dev
                  aws s3 ls s3://cf-cli-dev