name: "TEST Unit"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - v8
      - v7

permissions:
  contents: read

jobs: 
  test-unit:
    runs-on: ubuntu-latest
    name: test-unit
    defaults:
      run:
        shell: bash
    steps:
    - id: test-exit
      name: test-exit
      env:
        exit_code: ${{ vars.EXIT_CODE }}
      run: |
        exit $exit_code

