name: Min Capi

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
      - '.gitpod.yml'
      - 'README.md'

permissions:
  contents: read

jobs:
  shared-values:
    name: Shared Values
    runs-on: ubuntu-latest
    outputs:
      secrets-environment: ${{ steps.set-secrets-environment.outputs.secrets-environment }}
      go-version: ${{ steps.set-go-version.outputs.go-version }}
      min-capi: ${{ steps.get-min-capi.outputs.min-capi }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: set-secrets-environment
        name: Set environment
        run: echo "secrets-environment=PROD" >> $GITHUB_OUTPUT

      - id: set-go-version
        name: Parse Golang Version
        run: |
          go_version=($(grep -E '^go 1\.[[:digit:]]{1,2}' go.mod))
          echo "golang version: ${go_version[1]}"
          echo "go-version=${go_version[1]}" >> $GITHUB_OUTPUT

      - id: get-min-capi
        name: Get Minimum CAPI Version
        run: |
          min_capi=($(yq .cf-d-capi-version-min build_data.yml))
          echo "Minimum CAPI version: ${min_capi}"
          echo "min-capi=${min_capi}" >> $GITHUB_OUTPUT

## START min CAPI
  get-cf-env-with-min-capi:
    name: Setup CF env with MIN CAPI
    needs: shared-values
    uses: ./.github/workflows/cf-env-setup.yml
    with:
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      capi-version: ${{ needs.shared-values.outputs.min-capi}}
    secrets: inherit

  run-integration-tests-cf-env-with-min-capi:
    name: Integration tests with MIN CAPI
    needs:
      - shared-values
      - get-cf-env-with-min-capi
    uses: ./.github/workflows/run-integration-tests.yml
    with:
      go-version: ${{ needs.shared-values.outputs.go-version}}
      environment: ${{ needs.shared-values.outputs.secrets-environment }}
      environment-name: ${{ needs.get-cf-env-with-min-capi.outputs.environment-name }}
      run-with-client-creds: false

  # unclaim-cf-env-with-min-capi:
  #   name: Unclaim CF env with MIN CAPI
  #   needs:
  #     - shared-values
  #     - get-cf-env-with-min-capi
  #     - run-integration-tests-cf-env-with-min-capi
  #   if: always()
  #   uses: ./.github/workflows/cf-env-unclaim.yml
  #   with:
  #     environment: ${{ needs.shared-values.outputs.secrets-environment }}
  #     toolsmith-env-name: ${{ needs.get-cf-env-with-min-capi.outputs.environment-name }}
  #   secrets: inherit

## END min CAPI
